version: 2.1
orbs: 
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Instalcion dependecias
          command: npm i
      - run:
          name: build
          command: npm install --save-dev firebase-tools 
workflows:
  deploy_app:
    jobs:
      - build_and_test
 
