version: 2.1
orbs: 
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Instalcion dependecias
          command: npm i && npm install --save-dev firebase-tools
      - run:
          name: build
          command: ./node_modules/.bin/firebase deploy --token=1//05zhurgPHzk2PCgYIARAAGAUSNwF-L9IrKr9nnsTEfWWoAzgUzwq6wNb_UNKU6d3MXd6IV1LcqJX9cI_WRuPbAqgwBMbM-a-0j2Y
workflows:
  deploy_app:
    jobs:
      - build_and_test
 
