version: 2.1
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Instalcion dependecias
          command: npm i
workflows:
  deploy_app:
    jobs:
      - build_and_test
      
