version: 2.1
orbs: 
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Instalcion dependecias
          command: npm i && npm install --save-dev firebase-tools
      - run:
          command: npm run build && npm run export
      - run:
          name: deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  deploy_app:
    jobs:
      - build_and_test
 
