name: Release

on: 
  push:
    branches:
      - aws-actions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
              aws-access-key-id: AKIA4AVIDWXQ6GNKMC3Y
              aws-secret-access-key: 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
              aws-region: us-west-2
      - name: Inicio sesion
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag and push
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t tinderpuce -f ./Dockerfile
        
